#!/bin/bash
set -e

# Stop WeatherWorks if running
pm2 delete weatherworks || true
pm2 save

# Remove app directory
rm -rf /opt/weatherworks

# Remove desktop files
rm -f /usr/share/applications/weatherworks.desktop
rm -f /usr/share/applications/weatherworks-build.desktop

# Remove database initialization script
rm -f /usr/local/bin/weatherworks-init-db

exit 0
